import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientWrapper } from "./components/layout/client-wrapper";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { AuthGuard } from "./components/layout/AuthGuard";
import TopBar from "./components/layout/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lune",
  description: "Generated by create next app",
  icons: {
    icon: "/img/logo/fix-logo_1.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthGuard>
          <ReactQueryProvider>
            <ClientWrapper>
              <div className="sticky top-0 z-30">
                <TopBar />
              </div>{" "}
              {children}
            </ClientWrapper>
          </ReactQueryProvider>
        </AuthGuard>
      </body>
    </html>
  );
}
